@host = https://localhost:7063

GET {{host}}/dinners
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiZDNmMDJmZC1kOWYyLTQ0YTUtOTA4MC1jMzdhOGNkMDI0NDgiLCJnaXZlbl9uYW1lIjoiWmVlc2hhbiIsImZhbWlseV9uYW1lIjoiSXFiYWwiLCJqdGkiOiJhNzQ0MzgxNi0wOWRlLTRiYWQtOGFmMS1mYWQ2OWFjMjk2ZjEiLCJleHAiOjE3MjQ0OTM1MTAsImlzcyI6IkJ1YmVyIiwiYXVkIjoiQnViZXIifQ._4jiL2GjiFPxfyOiE_VGzxeCRu5s0QhwJ8PMFB8MsAY